services:
  backend:
    build: .
    environment:
      - PORT=4000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'bun -e "fetch(''http://localhost:$$PORT'').then(res => res.ok)"',
        ]
      interval: 1s
      timeout: 1s
      retries: 20
    networks:
      - lufin
