name: Testing
permissions:
  contents: read

on:
  push:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make start script executable
        run: chmod +x docker/get-docker-compose-params.sh test/start-all.sh lib/docker-build.sh
      - name: Run tests
        run: ./test/start-all.sh
