services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    environment:
      - DOMAIN=${DOMAIN}
      - BACKEND_PORT=${BACKEND_PORT:-3000}
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - lufin_frontend:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
  lufin_frontend:
    external: true