name: Testing
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make start script executable
        run: chmod +x test/start.sh
      - name: Run integration tests
        working-directory: test
        run: ./start.sh
