name: Testing
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make start script executable
        run: chmod +x docker/get-docker-compose-params.sh test/start-all.sh lib/docker-build.sh
      - name: Run integration tests
        working-directory: ./test
        run: ./start-all.sh
